version: 2
updates:
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 1
    reviewers:
      - 'alexanderczigler'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 1
    reviewers:
      - 'alexanderczigler'
    schedule:
      interval: 'weekly'
