name: Publish

on:
  push:
    branches:
      - main

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run export

      - name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'www.backliden.se'
          project: '__sapper__/export'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
