name: Smoketest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
          npm ci
          npx playwright install
          npm run smoketest
